export default [
  {
    _id: "123",
    username: "alice",
    password: "alice123",
    firstName: "Alice",
    lastName: "Wonderland",
    email: "alice@kambaz.edu",
    dob: "2001-01-15",
    loginId: "alice",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2020-10-01",
    totalActivity: "10:00:00",
  },
  {
    _id: "234",
    username: "bob",
    password: "bob123",
    firstName: "Bob",
    lastName: "Hope",
    email: "bob@kambaz.edu",
    dob: "2001-02-16",
    loginId: "bob",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2020-10-02",
    totalActivity: "11:00:00",
  },
  {
    _id: "345",
    username: "charlie",
    password: "charlie123",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie@kambaz.edu",
    dob: "2001-03-17",
    loginId: "charlie",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2020-10-03",
    totalActivity: "12:00:00",
  },
  {
    _id: "456",
    username: "dan",
    password: "dan123",
    firstName: "Dan",
    lastName: "Aykroyd",
    email: "dan@kambaz.edu",
    dob: "2001-04-18",
    loginId: "dan",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2020-10-04",
    totalActivity: "13:00:00",
  },
  {
    _id: "567",
    username: "eve",
    password: "eve123",
    firstName: "Eve",
    lastName: "Polastri",
    email: "eve@kambaz.edu",
    dob: "2001-05-19",
    loginId: "eve",
    section: "S101",
    role: "STUDENT",
    lastActivity: "2020-10-05",
    totalActivity: "14:00:00",
  },
  {
    _id: "789",
    username: "grace",
    password: "grace123",
    firstName: "Grace",
    lastName: "Hopper",
    email: "grace@kambaz.edu",
    dob: "1985-12-09",
    loginId: "grace",
    section: "FACULTY",
    role: "FACULTY",
    lastActivity: "2020-10-06",
    totalActivity: "15:00:00",
  },
  {
    _id: "791",
    username: "admin",
    password: "admin123",
    firstName: "Ada",
    lastName: "Admin",
    email: "admin@kambaz.edu",
    dob: "1980-01-01",
    loginId: "admin",
    section: "ADMIN",
    role: "ADMIN",
    lastActivity: "2020-10-08",
    totalActivity: "17:00:00",
  },
  {
    _id: "792",
    username: "ta",
    password: "ta123",
    firstName: "Taylor",
    lastName: "Assistant",
    email: "ta@kambaz.edu",
    dob: "1992-02-02",
    loginId: "ta",
    section: "TA",
    role: "TA",
    lastActivity: "2020-10-09",
    totalActivity: "18:00:00",
  },
  {
    _id: "793",
    username: "instructor",
    password: "instructor123",
    firstName: "Indigo",
    lastName: "Instructor",
    email: "instructor@kambaz.edu",
    dob: "1988-03-03",
    loginId: "instructor",
    section: "INSTRUCTOR",
    role: "INSTRUCTOR",
    lastActivity: "2020-10-10",
    totalActivity: "19:00:00",
  },
  {
    _id: "890",
    username: "heidi",
    password: "heidi123",
    firstName: "Heidi",
    lastName: "Klum",
    email: "heidi@kambaz.edu",
    dob: "2001-06-20",
    loginId: "heidi",
    section: "S102",
    role: "STUDENT",
    lastActivity: "2020-10-07",
    totalActivity: "16:00:00",
  },
];
